#!/usr/bin/env bash
# Rebuild the Claude.ai chat-skills bundle from .claude/skills/.
#
# Classification:
#   1. Heuristic: a skill containing an executable script (.py/.js/.sh/.cjs/.ps1/.mjs)
#      is machine-only (Claude Code); everything else is chat-friendly.
#   2. Overrides: names listed in force-exclude.txt are excluded even if script-free
#      (markdown-only skills that still need CLIs/MCP/git); names in force-include.txt
#      are included even if they contain scripts. One name per line, '#' comments ok.
#
# Outputs:
#   - dist/everything-ai-chat-skills.zip  (skills/ + zips/ + docs)
#   - MANIFEST.md and EXCLUDED.md are REGENERATED here (do not hand-edit)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SK="$ROOT/.claude/skills"
OUT="$ROOT/chat-skills-bundle"
BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT
mkdir -p "$BUILD/skills" "$BUILD/zips"

read_list() { [ -f "$1" ] && sed 's/#.*//; s/[[:space:]]*$//' "$1" | grep -v '^$' || true; }
FORCE_EXCLUDE="$(read_list "$OUT/force-exclude.txt")"
FORCE_INCLUDE="$(read_list "$OUT/force-include.txt")"
in_list() { printf '%s\n' "$2" | grep -qx "$1"; }

# Extract the frontmatter description (inline or '>-' folded block), single line.
skill_desc() {
  awk '
    NR==1 && $0=="---" {fm=1; next}
    fm && $0=="---" {exit}
    fm && /^description:/ {
      d=$0; sub(/^description:[[:space:]]*/,"",d)
      if (d==">-"||d==">"||d=="|"||d=="|-") {block=1; next}
      gsub(/^["'\'']|["'\'']$/,"",d); out=d; next
    }
    block && /^[[:space:]]+/ {line=$0; sub(/^[[:space:]]+/,"",line); out=out (out==""?"":" ") line; next}
    block {block=0}
    END {print out}
  ' "$1"
}

chat=(); excluded_scripts=(); excluded_forced=()
for d in "$SK"/*/; do
  name="$(basename "$d")"
  has_scripts=""
  [ -n "$(find "$d" -type f \( -name '*.py' -o -name '*.js' -o -name '*.sh' \
        -o -name '*.cjs' -o -name '*.ps1' -o -name '*.mjs' \) -print -quit)" ] && has_scripts=1

  if in_list "$name" "$FORCE_EXCLUDE"; then
    excluded_forced+=("$name")
  elif [ -n "$has_scripts" ] && ! in_list "$name" "$FORCE_INCLUDE"; then
    excluded_scripts+=("$name")
  else
    chat+=("$name")
    cp -R "$d" "$BUILD/skills/$name"
    (cd "$BUILD/skills" && zip -qr "$BUILD/zips/$name.zip" "$name")
  fi
done

# --- Regenerate MANIFEST.md ---
{
  echo "# Chat Skills Manifest"
  echo
  echo "Chat-friendly skills packaged for upload to **Claude.ai → Settings → Capabilities → Skills**."
  echo "Generated by \`build-bundle.sh\` — do not hand-edit. Total: ${#chat[@]} skills."
  echo
  echo "| # | Skill | Description |"
  echo "|---|-------|-------------|"
  i=0
  for name in "${chat[@]}"; do
    i=$((i+1))
    desc="$(skill_desc "$SK/$name/SKILL.md" | cut -c1-160 | sed 's/|/\\|/g')"
    echo "| $i | \`$name\` | $desc |"
  done
} > "$OUT/MANIFEST.md"

# --- Regenerate EXCLUDED.md ---
{
  echo "# Not Included (Claude Code / machine-only)"
  echo
  total_excluded=$(( ${#excluded_scripts[@]} + ${#excluded_forced[@]} ))
  echo "These $total_excluded skills need a real execution environment (local files, OS tools,"
  echo "external CLIs/APIs, or MCP servers) that the Claude.ai chat sandbox does not provide."
  echo "Keep them in Claude Code. Generated by \`build-bundle.sh\` — do not hand-edit."
  echo
  echo "## Contain executable scripts"
  echo
  for name in "${excluded_scripts[@]}"; do echo "- \`$name\`"; done
  echo
  echo "## Manually excluded (markdown-only but require CLIs, MCP servers, or git)"
  echo
  for name in "${excluded_forced[@]}"; do echo "- \`$name\`"; done
} > "$OUT/EXCLUDED.md"

cp "$OUT/README.md" "$OUT/MANIFEST.md" "$OUT/EXCLUDED.md" "$BUILD/" 2>/dev/null || true
[ -f "$ROOT/ATTRIBUTIONS.md" ] && cp "$ROOT/ATTRIBUTIONS.md" "$BUILD/"
mkdir -p "$OUT/dist"
rm -f "$OUT/dist/everything-ai-chat-skills.zip"
(cd "$BUILD" && zip -qr "$OUT/dist/everything-ai-chat-skills.zip" .)
echo "chat-friendly: ${#chat[@]} | excluded: $(( ${#excluded_scripts[@]} + ${#excluded_forced[@]} )) (scripts: ${#excluded_scripts[@]}, forced: ${#excluded_forced[@]})"
echo "bundle -> $OUT/dist/everything-ai-chat-skills.zip"
